---
- name: Install Apache.
  hosts: all
  become: true

  # vars_files:
  #   - vars/apache_default.yml
  #   - vars/apache_{{ ansible_os_family }}.yml

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted
    - name: restart memcached
      service:
        name: memcached
        state: restarted

  pre_tasks:
    include_vars: "{{ item }}"
    with_first_found:
      - "apache_{{ ansible_os_family }}.yml"
      - "apache_default.yml"

  tasks:
    - name: Add an environment variable to the remote user's shell.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_var='
        line: 'ENV_VAR=value'

    - name: Get the value of an environment variable.
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo
    
    - debug: msg="The variable is {{ foo.stdout }}"

    - name: Ensure Apache is installed.
      yum:
        name: "{{ apache_package }}"
        state: present

    - name: Copy test config file.
      copy:
        src: files/test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify: 
        - restart apache
        - restart memcached

    - name: Make sure handlers are flushed immediately. 
      meta: flush_handlers

    - name: Ensure Apache is running and starts at boot.
      service:
        name:  "{{ apache_service }}"
        state: started
        enabled: true