---
- hosts: all
  
  vars:
    my_color_choice: 'red'
  
  tasks:
    - name: "Verify {{ my_color_choice }} is a form of blue"
      assert:
        that: my_color_choice is local.colors.blue
          # > 
          # my_color_choice == 'blue'
          # or my_color_choice == '#0000ff'