Include your documentation here
---
- name: Install Apache.
  hosts: all

  tasks:
    - name: Install Apache.
      commad: yum install --quiet -y httpd httpd-devel
    - name: Copy configuration files.
      # possible to run shell via yaml :
      # shell: | <= used to merge several lines with \n
      #   your shell command 1
      #   your shell command 2
      #   ...
      #
      command: > # '>' <= Used to merge several commands with \n for the "command"
        cp httpd.conf /etc/httpd/conf/httpd.conf 
    - command: >
        cp httpd-vhosts /etc/httpd/conf/httpd-vhosts.conf
    - name: Start Apache and configure it to run at boot
      command: service httpd start
    - command: chkconfig httpd on